import { useEffect, useState } from 'react';
import type { RecognitionResult } from '../api/types';

interface Props { result: RecognitionResult | null; loading: boolean; onReview: (correctedValue: string) => Promise<void>; }

export function PredictionResult({ result, loading, onReview }: Props) {
  const [editing, setEditing] = useState(false); const [value, setValue] = useState('');
  const [reviewState, setReviewState] = useState<'idle' | 'loading'>('idle'); const [reviewError, setReviewError] = useState<string | null>(null);
  useEffect(() => { setEditing(false); setValue(result?.value ?? ''); setReviewError(null); setReviewState('idle'); }, [result]);
  if (loading) return <aside className="result-panel loading-result"><span className="spinner large" /><h2>Analyse en cours</h2><p>Lecture de la zone postale et calcul du niveau de confiance.</p><div className="skeleton" /><div className="skeleton short" /></aside>;
  if (!result) return <aside className="result-panel empty-result"><div className="empty-result-content"><div className="result-icon">⌁</div><div><p className="empty-result-label">RÉSULTAT</p><h2>En attente d’analyse</h2><p>Le code détecté, le niveau de confiance et les actions de validation apparaîtront ici.</p></div></div><div className="empty-result-footer"><span className="status-dot" /> Aucun résultat à valider</div></aside>;
  const confidence = result.confidence === null ? null : Math.round(result.confidence * 100);
  const expectedLength = result.kind === 'postal-code' ? 5 : 1;
  const saveCorrection = async () => {
    if (!new RegExp(`^\\d{${expectedLength}}$`).test(value)) { setReviewError(`Entrez exactement ${expectedLength} chiffre${expectedLength > 1 ? 's' : ''}.`); return; }
    setReviewState('loading'); setReviewError(null);
    try { await onReview(value); setEditing(false); } catch (error) { setReviewError(error instanceof Error ? error.message : 'La correction n’a pas pu être enregistrée.'); } finally { setReviewState('idle'); }
  };
  const displayedValue = result.value ?? '—';
  return <aside className="result-panel result-ready"><div className="result-label"><span className={result.requiresManualReview ? 'status review' : 'status success'}>{result.requiresManualReview ? 'À VÉRIFIER' : result.review ? 'CORRIGÉ' : 'VALIDÉ'}</span><span>{confidence === null ? 'Score indisponible' : `Score ${confidence}%`}</span></div><h2>{result.kind === 'postal-code' ? 'Code postal détecté' : 'Chiffre détecté'}</h2>{editing ? <div className="correction"><input value={value} onChange={(event) => setValue(event.target.value.replace(/\D/g, '').slice(0, expectedLength))} aria-label="Valeur corrigée" autoFocus disabled={reviewState === 'loading'} /><button onClick={saveCorrection} disabled={reviewState === 'loading'}>{reviewState === 'loading' ? 'Enregistrement…' : 'Enregistrer'}</button><small>Entrez {expectedLength} chiffre{expectedLength > 1 ? 's' : ''}.</small>{reviewError && <p className="review-error" role="alert">{reviewError}</p>}</div> : <><div className="postal-code" aria-label={`Lecture ${displayedValue}`}>{displayedValue.split('').map((digit, index) => <span key={index} className={result.predictions[index]?.confidence !== null && result.predictions[index].confidence < .75 ? 'uncertain' : ''}>{digit}</span>)}</div><div className="confidence"><div><span style={{ width: `${confidence ?? 0}%` }} /></div><p>{confidence === null ? 'Score non disponible' : `Score du modèle : ${confidence}%`}</p></div></>}{result.kind === 'postal-code' && result.predictions.length > 0 && <div className="digit-list">{result.predictions.map((prediction, index) => <span key={index}>{prediction.digit}<small>{prediction.confidence === null ? '—' : `${Math.round(prediction.confidence * 100)}%`}</small></span>)}</div>}{result.requiresManualReview && !editing && <div className="review-callout"><b>Contrôle opérateur requis</b><p>{result.reasons.length ? `Motif : ${result.reasons.join(', ')}.` : 'Comparez avec l’image avant validation.'}</p></div>}{result.review && <div className="review-summary"><span>Correction opérateur</span><strong>{result.review.correctedValue}</strong>{result.originalValue !== result.review.correctedValue && <small>Lecture initiale : {result.originalValue ?? 'indisponible'}</small>}</div>}{!editing && <button className="secondary-button" onClick={() => setEditing(true)}>{result.review ? 'Modifier la correction' : result.requiresManualReview ? 'Corriger la lecture' : 'Confirmer ou modifier'}</button>}<p className="result-meta">Source : {result.kind === 'postal-code' ? 'zone postale recadrée' : 'dessin manuel'} · {result.createdAt ? new Date(result.createdAt).toLocaleString('fr-FR') : 'Résultat temporaire'}</p></aside>;
}
