import { useEffect, useState } from 'react';
import type { RecognitionResult } from '../api/types';
interface Props { result: RecognitionResult | null; loading: boolean; onCorrection: (result: RecognitionResult) => void; }
export function PredictionResult({ result, loading, onCorrection }: Props) {
  const [editing, setEditing] = useState(false); const [value, setValue] = useState('');
  useEffect(() => { setEditing(false); setValue(result?.value ?? ''); }, [result]);
  if (loading) return <aside className="result-panel loading-result"><span className="spinner large" /><h2>Analyse en cours</h2><p>Lecture de la zone postale et calcul du niveau de confiance.</p><div className="skeleton" /><div className="skeleton short" /></aside>;
  if (!result) return <aside className="result-panel empty-result"><div className="empty-result-content"><div className="result-icon">⌁</div><div><p className="empty-result-label">RÉSULTAT</p><h2>En attente d’analyse</h2><p>Le code détecté, le niveau de confiance et les actions de validation apparaîtront ici.</p></div></div><div className="empty-result-footer"><span className="status-dot" /> Aucun résultat à valider</div></aside>;
  const confidence = Math.round(result.confidence * 100);
  const saveCorrection = () => { if ((result.kind === 'postal-code' && /^\d{5}$/.test(value)) || (result.kind === 'digit' && /^\d$/.test(value))) { onCorrection({ ...result, value, requiresManualReview: false }); setEditing(false); } };
  return <aside className="result-panel result-ready"><div className="result-label"><span className={result.requiresManualReview ? 'status review' : 'status success'}>{result.requiresManualReview ? 'À VÉRIFIER' : 'VALIDÉ'}</span><span>{confidence}% de confiance</span></div><h2>{result.kind === 'postal-code' ? 'Code postal détecté' : 'Chiffre détecté'}</h2>{editing ? <div className="correction"><input value={value} onChange={(event) => setValue(event.target.value.replace(/\D/g, '').slice(0, result.kind === 'postal-code' ? 5 : 1))} aria-label="Valeur corrigée" autoFocus /><button onClick={saveCorrection}>Enregistrer</button><small>Entrez {result.kind === 'postal-code' ? '5 chiffres' : '1 chiffre'}.</small></div> : <><div className="postal-code" aria-label={`Lecture ${result.value}`}>{result.value.split('').map((digit, index) => <span key={index} className={result.predictions[index]?.confidence < .75 ? 'uncertain' : ''}>{digit}</span>)}</div><div className="confidence"><div><span style={{ width: `${confidence}%` }} /></div><p>Confiance {result.confidenceLevel === 'high' ? 'élevée' : result.confidenceLevel === 'medium' ? 'à confirmer' : 'faible'}</p></div></>}{result.kind === 'postal-code' && <div className="digit-list">{result.predictions.map((prediction, index) => <span key={index}>{prediction.digit}<small>{Math.round(prediction.confidence * 100)}%</small></span>)}</div>}{result.requiresManualReview && !editing && <div className="review-callout"><b>Contrôle opérateur requis</b><p>Un ou plusieurs chiffres sont incertains. Comparez avec le courrier avant validation.</p></div>}{!editing && <button className="secondary-button" onClick={() => setEditing(true)}>{result.requiresManualReview ? 'Corriger la lecture' : 'Modifier la prédiction'}</button>}<p className="result-meta">Source : {result.kind === 'postal-code' ? 'image de courrier' : 'dessin manuel'} · Résultat temporaire</p></aside>;
}
