FROM node:22-alpine AS build
WORKDIR /app
ARG VITE_USE_MOCKS=false
ENV VITE_USE_MOCKS=$VITE_USE_MOCKS
COPY front/package*.json ./
RUN npm ci
COPY front/ .
COPY deploy/nginx.conf /tmp/nginx.conf
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /tmp/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80 443
